seed: 1
control_mode: 'position'

mpc_sample_num: 1500
mpc_horizon: 3

defaults:
  - env: sim_not_render
  - high_level_control: FOOT_random
  - low_level_control: IK
  - rollout: traj_tracking
  - hydra/run: customized