seed: 3
control_mode: 'position'

mpc_sample_num: 1500
mpc_horizon: 3

defaults:
  - env: sim_not_render
  - high_level_control: LAT_random_3
  - low_level_control: LAT_3
  - rollout: vel_tracking
  - hydra/run: customized