seed: 4
control_mode: 'position'

mpc_sample_num: 10000
mpc_horizon: 3

defaults:
  - env: sim_not_render
  - high_level_control: LAT_random_4
  - low_level_control: LAT_4
  - rollout: vel_tracking
  - hydra/run: customized