seed: 100
control_mode: 'position'

mpc_sample_num: 1000
mpc_horizon: 3

defaults:
  - env: sim_not_render
  - high_level_control: SAC
  - low_level_control: IK
  - rollout: SAC_learning
  - hydra/run: customized