a_dim: 18
batch_size: 512
control_frequency: 60
control_mode: position
high_level_policy_type: random
low_level_buffer_size: 10000
low_level_policy_type: NN
model_hidden_num: 512
model_layer_num: 3
model_lr: 0.001
model_update_steps: 10000
mpc_horizon: 3
mpc_sample_num: 1000
num_iters: 2000
num_latent_action_per_iteration: 10
num_timestep_per_footstep: 100
policy_size: 512
render: false
seed: 4
sim: true
test: 0
update_low_level_policy: 0
update_sample_policy: 0
update_sample_policy_lr: 0.001
z_dim: 4
