a_dim: 18
batch_size: 64
control_frequency: 60
control_mode: position
high_level_policy_type: SAC
low_level_buffer_size: 10000
low_level_policy_type: IK
model_hidden_num: 64
model_lr: 0.001
model_update_steps: 10
mpc_horizon: 3
mpc_sample_num: 1500
num_iters: 3
num_timestep_per_footstep: 50
policy_size: 512
render: false
seed: 2
sim: true
test: 1
update_low_level_policy: 0
update_sample_policy: 10
update_sample_policy_lr: 0.001
z_dim: 3
