a_dim: 18
batch_size: 64
control_frequency: 60
control_mode: position
high_level_policy_type: raibert
low_level_buffer_size: 10000
low_level_policy_type: IK
model_hidden_num: 16
model_lr: 0.001
model_update_steps: 1500
mpc_horizon: 3
mpc_sample_num: 1000
num_iters: 1000
num_latent_action_per_iteration: 10
num_timestep_per_footstep: 50
policy_size: 512
render: false
seed: 3
sim: true
test: 0
update_low_level_policy: 0
update_sample_policy: 0
update_sample_policy_lr: 0.001
z_dim: 3
